name: Laravel Prod Deploy

on: [push]

jobs:
  laravel-compile:
    runs-on: self-hosted
    steps:
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Migrate
      run: php artisan migrate
    - name: Compile Assets
      run: npm run prod
